### ISSUE TITLE
アプリが起動しない: [IMKServer _createConnection] could not register dev.ensan.inputmethod.azooKeyMac_Connection

### ISSUE THREAD

**Issue by gfx** [ensan-hcl/azooKey-Desktop#29]
https://github.com/ensan-hcl/azooKey-Desktop/releases/tag/v0.1.0-alpha.7 を手元のmacOSにインストールしてログアウト＆再ログインをしてみたところ、IMが追加されている気配がありませんでした。試しにコンソールからバイナリを直接起動してみると、次のようなログが出ました。

```
$ /Library/Input\ Methods/azooKeyMac.app/Contents/MacOS/azooKeyMac
2024-08-02 10:35:48.086 azooKeyMac[14455:218711] [IMKServer _createConnection] could not register dev.ensan.inputmethod.azooKeyMac_Connection
2024-08-02 10:35:48.086 azooKeyMac[14455:218711] [IMKServer initWithName:bundleIdentifier:]: [IMKServer _createConnection]: *Failed* to register NSConnection name=dev.ensan.inputmethod.azooKeyMac_Connection
2024-08-02 10:35:48.087 azooKeyMac[14455:218711] tried connection
```

環境:

* Machine: Macbook Pro 2021
* Chip: Apple M1 Pro
* macOS: Sonoma 14.5

azooKeyを触るのは初めてで、別の開発版のazooKeyがどこかにインストールされている、などはありません。

**Comment by ensan-hcl** [comment]
「設定」アプリからazooKey on macOSを追加する必要がありますが、この画面にazooKeyが表示されていないということでしょうか？
![image](https://github.com/user-attachments/assets/19f95f81-dba8-4b56-8f59-47d081cd3779)

**Comment by gfx** [comment]
ありません。もしかしたらOSの言語を英語にしていることが関係しているのかも…？

<img width="676" alt="Screenshot 2024-08-06 at 10 13 55" src="https://github.com/user-attachments/assets/562aa458-9f06-4b1b-87f7-be46c787ed0e">

**Comment by gfx** [comment]
`install.sh` でビルド＆インストールを試したところ、azooKeyが使える状態になりました！！！

<img width="200" alt="Screenshot 2024-08-06 at 10 25 09" src="https://github.com/user-attachments/assets/2d4c259f-d216-46cb-b2d2-d1deef4864b4">

**Comment by ensan-hcl** [comment]
一旦良かったです！解決済みとしてcloseします！
