### ISSUE TITLE
pkgファイルをDeveloper ID Installer証明書で署名してほしい

### ISSUE THREAD

**Issue by mtgto** [ensan-hcl/azooKey-Desktop#61]
ReleasesページからダウンロードしたpkgファイルをmacOS 14.6.1で開こうとしたところ、署名されてない旨のエラーが表示されました。

<img width="260" alt="image" src="https://github.com/user-attachments/assets/7e1e1197-67c3-4e03-95c3-4a056ba89583">

```console
❯ pkgutil --check-signature ~/Downloads/azooKey-release.pkg
Package "azooKey-release.pkg":
   Status: no signature
```

pkgに "Developer ID Installer" 証明書で署名をつけてもらえるとこのような警告が出なくなるので、利用者が安心して使えるのではないかと思います。ご検討いただければ幸いです。
https://developer.apple.com/jp/help/account/create-certificates/create-developer-id-certificates

参考: 試しに私のDeveloper ID Installer署名で署名してみたもの

```console
❯ productsign --sign "Developer ID Installer" ~/Downloads/azooKey-release.pkg ~/Downloads/azooKey-release-signed.pkg
productsign: using timestamp authority for signature
productsign: signing product with identity "Developer ID Installer: Satoshi Gotou (W3A6B7FDC7)" from keychain /Users/user/Library/Keychains/login.keychain-db
productsign: adding certificate "Developer ID Certification Authority"
productsign: adding certificate "Apple Root CA"
productsign: Wrote signed product archive to /Users/xxxx/Downloads/azooKey-release-signed.pkg
```

```console
❯ pkgutil --check-signature ~/Downloads/azooKey-release-signed.pkg
Package "azooKey-release-signed.pkg":
   Status: signed by a developer certificate issued by Apple for distribution
   Signed with a trusted timestamp on: 2024-08-24 02:30:41 +0000
   Certificate Chain:
    1. Developer ID Installer: Satoshi Gotou (W3A6B7FDC7)
       Expires: 2027-02-01 22:12:15 +0000
       SHA256 Fingerprint:
           4B 04 F9 16 DA 30 68 EC 00 BC 5B B5 F6 E2 C4 88 FC 22 A3 F7 F3 1B
           A1 A5 06 B7 54 27 01 0B 37 12
       ------------------------------------------------------------------------
    2. Developer ID Certification Authority
       Expires: 2027-02-01 22:12:15 +0000
       SHA256 Fingerprint:
           7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03
           F2 9C 88 CF B0 B1 BA 63 58 7F
       ------------------------------------------------------------------------
    3. Apple Root CA
       Expires: 2035-02-09 21:40:36 +0000
       SHA256 Fingerprint:
           B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C
           68 C5 BE 91 B5 A1 10 01 F0 24
```

**Comment by ensan-hcl** [comment]
ありがとうございます！以下に署名付きのazooKey-release-signed.pkgを追加してみたので、お試しいただけますか？
https://github.com/ensan-hcl/azooKey-Desktop/releases/tag/v0.1.0-alpha.9

**Comment by mtgto** [comment]
@ensan-hcl うっ macOS 14.5.1環境では azooKey-release-signed.pkg でも同様にアラートが表示されました。
<img width="260" alt="image" src="https://github.com/user-attachments/assets/a9131dc7-1323-47c0-953a-afe26376a445">

自分が配布していているpkgをどうしてたっけと思ってみたのですが、pkgを署名した後にAppleの公称 (Notarization) を受けており、その作業が恐らく必要なのにそれが抜けていているためと思います。
Issue説明では間違った (不十分な) 提案でもうしわけありません、

手順としてはこの記事の「2)次に pkg を distibution形式にします。」「3)最後にsignしておわり」までやる必要があると思われます。
https://qiita.com/ioue/items/9d1681286c50f8e7e98d#2-%E6%AC%A1%E3%81%AB-pkg-%E3%82%92-distibution%E5%BD%A2%E5%BC%8F%E3%81%AB%E3%81%97%E3%81%BE%E3%81%99

私のアプリではpkgを署名、Appleの公称を受けた後に `stapler staple xxx.pkg` で上記記事の「6) stapleをはります。」の処理を行っているようでした。
https://github.com/mtgto/macSKK/blob/1.1.0/Makefile#L63-L69

**Comment by ensan-hcl** [comment]
なるほど！notarytool submitとstapler stapleまで行ってみたので、お試しいただけますか？私の環境では警告表示がなくなったようです。

**Comment by mtgto** [comment]
試してみました。私の環境 (macOS 14.6.1 と まだ一回もpkgを開いてなかったmacOS 13.6.9) で警告表示が出ずにインストーラが起動しました! よさそうです! 🙏 

> notarytool submitとstapler stapleまで行ってみたので

蛇足です。notarizedは行われているようですが、stapleしたあとはReleasesに再アップロードしないとおそらくstapleされてない状態だと思います。(#62 で次リリースからstapleされたファイルになるようなので再度アップロードしていただかなくても大丈夫です)
https://stackoverflow.com/a/57918071 を参考にしました。

#### spctlを使ってpkgが公称通っていることを確認

```console
❯ spctl -a -vvv -t install ~/Downloads/azooKey-release-signed.pkg
/Users/xxx/Downloads/azooKey-release-signed.pkg: accepted
source=Notarized Developer ID
origin=Developer ID Installer: Keita Miwa (9S3UXHYP65)
```

#### staplerコマンドで見るとstapleされたバイナリではなさそう

```console
❯ xcrun stapler validate ~/Downloads/azooKey-release-signed.pkg
Processing: /Users/xxx/Downloads/azooKey-release-signed.pkg
azooKey-release-signed.pkg does not have a ticket stapled to it.
```

stapleされていると `The validate action worked!` のような表示になると思います。

```console
❯ xcrun stapler validate /Volumes/macSKK/macSKK-1.1.0.pkg
Processing: /Volumes/macSKK/macSKK-1.1.0.pkg
The validate action worked!
```

**Comment by ensan-hcl** [comment]
ご確認いただきありがとうございます！Stapleの方は仰る通りで、次以降のリリースではStaple済みのものが載るようになると思います！

**Comment by mtgto** [comment]
対応ありがとうございました! 最初不十分な説明で失礼いたしました 🙇
