### ISSUE TITLE
bug: 英字キーボードにて「＞」「＜」が入力できない。

### ISSUE THREAD

**Issue by in-noob** [ensan-hcl/azooKey-Desktop#91]
もともとの仕様なのか、英字キーボードなのかは未確認です。
ローマ字入力下において、「＞」「＜」の入力が行えませんでしたので、こちらに記載します。

**Comment by ensan-hcl** [comment]
これは不具合ですね！

**Comment by ensan-hcl** [comment]
メモ: この部分で`.shift`を考慮した処理にしないといけない

https://github.com/ensan-hcl/azooKey-Desktop/blob/8fca18011b394325cfca67a1c34f2e79d230416b/azooKeyMac/InputController/InputMode.swift#L102-L113
